Algoritmo "resolvendo soluções"

Var
largura, comprimento,valor, area, preco:real



Inicio


escreval("Digite a largura do terreno = ")
leia(largura)
escreval("Digite o comprimento do terreno = ")
leia(comprimento)
escreval("Digite o valor do metro quadrado = ")
leia(valor)
area<- largura*comprimento
escreval("Area do terreno = ", area)
preco<- area*valor
escreval("Preço do terreno = ", preco)






Fimalgoritmo